name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake (Dark)
        uses: Platane/snk@v3
        with:
          github_user_name: zicoovic
          outputs: snake.svg
          args: --theme dark  # الطريقة الصحيحة لاختيار الثيم الداكن

      - name: Upload snake.svg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: snake.svg
