name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # كل يوم منتصف الليل UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: zicoovic
          outputs: dist/snake.svg

      - name: Deploy snake.svg to snake branch using PAT
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: zicoovic/zicoovic
          publish_branch: snake
          publish_dir: ./dist
          keep_files: true
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
