name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # كل يوم منتصف الليل UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: zicoovic
          outputs: snake.svg

      - name: Commit snake.svg to snake branch using PAT
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B snake
          git add snake.svg
          git commit -m "Update GitHub Activity Snake" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/zicoovic/zicoovic.git snake --force
